server:
  port: 8081
spring:
  application:
    name: spring_security
  thymeleaf:
    cache: false
  profiles:
    # 可以配置多个。逗号分隔
    active: dev
  datasource:
    # 注意mysql 时区 字符集编码
    url: jdbc:mysql://127.0.0.1:3306/sys_manager?autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    # redis 配置
  redis:
    redisson:
      file: classpath:redisson.yml

#    redisson:
#      config: classpath:redisson.yml

  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  session:
    store-type: redis
    timeout:
      seconds: 900
oauth2:
  othersys:
    - name: github
      client_id: e1015c0a10dc5e11b718
      client_secret: 72e50f683c91861107320cddfdb2948c134b3c52
      redirectUri: http://localhost:8081/api/v1/oauth/callback/github
    - name: gitee
      client_id: 8d5f66c25383612cd6556e3b6273a2cddcf143be463b43b28902ed80bb89363f
      client_secret: 2882d5ce5db4b25c90746a85b29e49d220b3877a9b4f0263f46c5e277b4c4f5f
      redirectUri: http://localhost:8081/api/v1/oauth/callback/gitee
# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: fun.zyjk.spring_security.sys.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true


